version: '3'

networks:
  ecommerceapp:


services:
  db:
    container_name: db-ecommerce
    image: mcr.microsoft.com/mssql/server
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "A!a4765f8d7"
    ports:
      - "1433:1433"
    networks:
      - ecommerceapp
  web-api:
    container_name: api-ecommerce
    image: nepcode/api_ecommerce
    build: .
    environment:
      DB_HOST: "db"
      DB_PORT: "1433"
      DB_USER: "sa"
      DB_PASSWORD: "A!a4765f8d7"
      DB_NAME: "asp_netcore_ecommerce"
    depends_on:
      - db
    ports:
      - "8080:80"
    networks:
      - ecommerceapp